home-logueado.php, src/1.0.0/css/pages/home.css
=> DS-4321-Home-layout-v2

home-logueado.php, home.php, src/1.0.0/css/components/central-video.css, src/1.0.0/css/components/event-cards.css, src/1.0.0/css/general/constants.css, src/1.0.0/css/pages/home.css
=> DS-4397-Home-modifications

src/1.0.0/js/common/customsError.js, src/1.0.0/js/common/decodeEmail.js, src/1.0.0/js/common/formsValidators.js, src/1.0.0/js/common/index.js, src/1.0.0/js/common/utm.js, src/1.0.0/js/homeEcommerce.js
- feat: add custom error function
- feat: add functions to validate form
- feat: add function to decode email
- feat: add functions to get utms from url
- chore: barrel file
- feat: add submit logic for homeEccomerce
=> DS-4330_home_logic

admin/speakers/add_speakers.php, admin/speakers/edit_speakers.php
related to [httpsDS-4406://makingsense.atlassian.net/browse/DS-4406](https://makingsense.atlassian.net/browse/DS-4406)
=> DS-4406 fix speakers form no required inputs

ecommerce-registrado.php, ecommerce.php, index.php, registrado.php, src/components/head-ecommerce.php, src/components/head-home.php, src/components/head.php
=> DS-4334-Home-Ecommerce-SEO

ecommerce.php, index.php, src/1.0.0/css/general/constants.css, src/1.0.0/css/pages/home.css, src/1.0.0/js/common/decodeEmail.js, src/1.0.0/js/common/index.js, src/1.0.0/js/common/user.js, src/1.0.0/js/home.js, src/1.0.0/js/homeEcommerce.js
feat: user info redirect pages
=> DS-4330_fe_user_redirects

.docker/config/nginx/Dockerfile, .docker/config/nginx/nginx.conf
Related to: [DS-4437](https://makingsense.atlassian.net/browse/DS-4437)
[DS-4437]: https://makingsense.atlassian.net/browse/DS-4437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DS-4437 link nginx.conf file to manage http config

adm23/server/config/config.php, adm23/server/modules/sponsors/addSponsor.php, adm23/server/modules/sponsors/getSponsors.php, adm23/server/modules/sponsors/removeSponsor.php
Related to : [DS-4438](https://makingsense.atlassian.net/browse/DS-4438)
abm endpoints sponsors entity from admin module
[DS-4438]: https://makingsense.atlassian.net/browse/DS-4438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DS-4438 serve add get and remove sponsor endpoints

adm23/index.php, adm23/src/main.js, adm23/src/modules/navbar/navbar.html, adm23/src/modules/navbar/navbar.js
related to: [DS-4439](https://makingsense.atlassian.net/browse/DS-4439)
[DS-4439]: https://makingsense.atlassian.net/browse/DS-4439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DS-4439 navbar component for admin module

adm23/src/modules/sponsors/components/sponsors-list/getSponsors.js, adm23/src/modules/sponsors/components/sponsors-list/sponsors-list.html, adm23/src/modules/sponsors/components/sponsors-list/sponsorsList.js, adm23/src/modules/sponsors/components/sponsors-list/sponsorsRows.js
Related to:  [DS-4441](https://makingsense.atlassian.net/browse/DS-4441)
[DS-4441]: https://makingsense.atlassian.net/browse/DS-4441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DS-4441 sponsors list component

utils/Doppler.php
- fix: remove old params
- feat: save custom field emmsencodeemail in Doppler
=> DS-4443_encode_email

config.php, relay-confirmation-email/pre-template-email-register/20230228-EMMS.html, utils/Relay.php
- fix: change email subject
- feat: add email pre header
=> DS-4449_change_email_subjet_preheader

ecommerce-registrado.php, ecommerce.php, registrado.php
=> DS-4442_user_redirect

adm23/src/modules/sponsors/components/sponsor-form/hiddenFieldList.js, adm23/src/modules/sponsors/components/sponsor-form/sponsor-form.html, adm23/src/modules/sponsors/components/sponsor-form/sponsorForm.js, adm23/src/modules/sponsors/components/sponsors-list/sponsorsRows.js, adm23/src/modules/sponsors/types/sponsorTypes.js
Related to: [DS-4440](https://makingsense.atlassian.net/browse/DS-4440)
[DS-4440]: https://makingsense.atlassian.net/browse/DS-4440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DS-4440 sponsor form component

.docker/db/EMMS23.sql
Related at: [DS-4485](https://makingsense.atlassian.net/browse/DS-4485)
[DS-4485]: https://makingsense.atlassian.net/browse/DS-4485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DS-4485 data base update schema

ecommerce.php, index.php, registrado.php
=> DS-4415/16-Update-videos

ecommerce-registrado.php, ecommerce.php, index.php, registrado.php, src/1.0.0/css/components/event-cards.css, src/components/footer.php
=> DS-4487-Delete-emms-fintech

ecommerce.php
=> change-month

adm23/index.php, adm23/server/config/config.php, adm23/server/modules/sponsors/addSponsor.php, adm23/server/modules/sponsors/getSponsors.php, adm23/server/modules/sponsors/removeSponsor.php
Related to: [DS-4490](https://makingsense.atlassian.net/browse/DS-4490)
A Config Class implementation with connection db and vpn middleware.
[DS-4490]: https://makingsense.atlassian.net/browse/DS-4490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DS-4490 VPN security

ecommerce.php
**Siteground link was changed**
=> DS-4501-Change-siteground-link

src/1.0.0/css/components/event-cards.css
=> hotfix-post-deploy-eventcards

ecommerce-registrado.php, ecommerce.php, index.php, registrado.php, src/1.0.0/css/components/calendar.css, src/1.0.0/css/pages/ecommerce.css
=> DS-4509-Ecommerce-modifications

index.php, registrado.php, src/1.0.0/css/components/central-video.css, src/1.0.0/css/pages/home.css
=> DS-4509-Home-modifications

ecommerce-registrado.php, ecommerce.php, index.php, registrado.php, sponsors-registrado.php, sponsors.php, src/components/gtm.php, src/components/head.php
1. feat: add google tag manager tags
3. feat: implement gtm component
=> DS-4518_add_GTM

src/components/head-home.php
=> DS-4509-Home-SEO-modifications

index.php, src/1.0.0/css/pages/ecommerce.css
=> DS-4509-Visual-modifications

.docker/config/nginx/default.conf, ecommerce-registrado.php, ecommerce.php, index.php, registrado.php, sponsors.php
Related to [DS-4507](https://makingsense.atlassian.net/browse/DS-4507)
[DS-4507]: https://makingsense.atlassian.net/browse/DS-4507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DS-4507] nginx regrite php extensions

admin/speakers/edit_speakers.php
Related to: [DS-4489](https://makingsense.atlassian.net/browse/DS-4489)
[DS-4489]: https://makingsense.atlassian.net/browse/DS-4489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DS-4489 input speaker images

sponsors-registrado.php, sponsors.php, src/1.0.0/js/sponsors.js
- feat: submit & slug redirect logic
- feat: print sponsors in front
=> DS-4452_sponspors

sponsors-interna.php, sponsors.php, utils/DB.php
- fix: change redirect
- feat: end point to get sponsor by slug
- feat: implement sponsors interna
=> DS-4342_sponspor_interna_data

sponsors-interna.php
fix: change sponsors video to iframe
=> DS-4452-fix_sponsors_interna

services/register.php, utils/Doppler.php
feat: add industry in doppler field
=> DS-4495_add_instrustry_in_doppler

ecommerce-registrado.php, ecommerce.php, src/components/speakers.php
feat: change positon debate card
=> DS-4543_change_debate_card

index.php, sponsors-registrado.php, sponsors.php, src/1.0.0/css/components/calendar.css, src/1.0.0/css/pages/internal-sponsors.css
=> DS-4517-General-modifications

ecommerce.php, src/1.0.0/js/mediaPartners.js
fix: change load for partners exclusive
=> DS-4557_fix_sponsors_exclusive

ecommerce.php, sponsors-registrado.php, sponsors.php
fix: change sponsors display with dont have description
=> DS-4558_fix_sponsors

adm23/src/modules/sponsors/components/sponsor-form/sponsorForm.js, adm23/src/modules/sponsors/components/sponsors-list/sponsorsRows.js
Related to: [DS-4559](https://makingsense.atlassian.net/browse/DS-4559)
[DS-4559]: https://makingsense.atlassian.net/browse/DS-4559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DS-4559 fix update sponsors clear not required fields

sponsors-registrado.php
=> DS-4549-Post-deploy-modifications-v2

.docker/docker-compose.yml, adm23/server/config/config.php, config.php
Related to: [DS-4560](https://makingsense.atlassian.net/browse/DS-4560)
[DS-4560]: https://makingsense.atlassian.net/browse/DS-4560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DS-4560 refactor config admin docker env vars

sponsors-registrado.php, sponsors.php, utils/DB.php
- feat: add endpoint to get all visible sponsors
- feat: print visible sponsors card in front
=> DS-4563_sponsors_card

src/1.0.0/js/mediaPartners.js
fix: change in the declaration of the container variable
=> DS-4564_fix_console_error

adm23/server/modules/settings/getPhase.php, adm23/server/modules/settings/setPhase.php, adm23/src/modules/navbar/navbar.html, adm23/src/modules/navbar/navbar.js, adm23/src/modules/settings/phases/phases-list.html, adm23/src/modules/settings/phases/services/getPhase.js, adm23/src/modules/settings/phases/services/setPhase.js, adm23/src/modules/settings/phases/showPhasesList.js, adm23/src/modules/settings/settings.html, adm23/src/modules/settings/settings.js
Related to: [DS-4548](https://makingsense.atlassian.net/browse/DS-4548)
[DS-4548]: https://makingsense.atlassian.net/browse/DS-4548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Ds 4548 settings admin

adm23/src/modules/sponsors/components/sponsor-form/hiddenFieldList.js, adm23/src/modules/sponsors/components/sponsor-form/sponsor-form.html, adm23/src/modules/sponsors/components/sponsor-form/sponsorForm.js
Related to: [DS-4561](https://makingsense.atlassian.net/browse/DS-4561)
[DS-4561]: https://makingsense.atlassian.net/browse/DS-4561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: adm form sponsors checkbox to hide show in landing

adm23/src/modules/sponsors/components/sponsor-form/sponsorForm.js
Related to: [DS-4588](https://makingsense.atlassian.net/browse/DS-4588)
[DS-4588]: https://makingsense.atlassian.net/browse/DS-4588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: sponsors form upload image

services/register.php, src/1.0.0/js/common/submitForm.js, src/1.0.0/js/homeEcommerce.js, utils/DB.php
feat: change endpoint to add or update new event
feat: add event in user array
feat: remove localstorage logic
feat: add multiple events in local storage
=> DS-4565_send_events

services/register.php, utils/DB.php
fix: send event type to get phase
fix: insert event in subscriptons_doppler table
chore: indeed commit
=> DS-4565_fix_table

src/1.0.0/css/components/hero-registration.css, src/1.0.0/css/general/constants.css, src/1.0.0/js/dateCounter.js, src/components/date-counter.php, stages/ecommerce/pre/ecommerce.php
- feat: change in counter to print in multiple places
- feat: add new data-counter component for mobile
- feat: add new styles for data counter
=> DS-4597_change_form_place

digital-trends-registrado.php, digital-trends.php, ecommerce-registrado.php, ecommerce.php
=> DS-4430_fix_routes

index.php, registrado.php, src/1.0.0/css/components/event-cards.css, src/1.0.0/css/components/header.css, src/1.0.0/css/components/hellobar.css, src/1.0.0/css/styles.css, stages/ecommerce/pre/ecommerce-registrado.php, stages/ecommerce/pre/ecommerce.php
=> DS-4615-Home-new-day-modifications

src/1.0.0/js/date.js
=> DS-4591_fix_country_hour

src/1.0.0/css/components/calendar.css, src/1.0.0/css/components/hellobar.css, src/components/speakers.php
=> DS-4607-Clasification-speakers

utils/Relay.php
fix: add email for events type and current phase
=> /DS-4619_fix_email_for_events

src/1.0.0/css/components/calendar.css, src/components/speakers.php
=> DS-4607-Clasification-speakers-v2

stages/ecommerce/pre/ecommerce.php
=> fix-faq-ecommerce-cta

admin/speakers/edit_speakers.php, src/components/speakers.php
=> fix: speakers

adm23/server/modules/settings/getPhase.php, adm23/server/modules/settings/setTransmission.php, adm23/src/modules/settings/phases/phases-list.html, adm23/src/modules/settings/phases/services/setPhase.js, adm23/src/modules/settings/phases/showPhasesList.js
Related to: [DS-4621](https://makingsense.atlassian.net/browse/DS-4621)
[DS-4621]: https://makingsense.atlassian.net/browse/DS-4621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Ds 4621 transmission admin

src/1.0.0/js/date.js, src/components/speakers.php
fix: change hour
fix: change hour for spain country
=> DS-4626_fix_hour_esp

registrado.php, src/1.0.0/css/scripts/cards.css, src/1.0.0/css/styles.css, src/1.0.0/js/user.js
- feat: add styles for event card logic
- feat: add card logic for user event and live events
=> Ds 4622 registrado logic cards

config.php, src/1.0.0/css/components/hero-conference.css, stages/ecommerce/during/ecommerce-registrado.php
feat: add youtube, twitch and plaque logic
chore: update config
fix: change youtube chat height
=> DS-4475_DS-4587_live_youtube_and_logic

speaker-interna.php, src/1.0.0/css/components/certificate-modal.css, src/1.0.0/css/pages/ecommerce.css, src/1.0.0/js/speakersInterna.js, stages/digital-trends/pre/digital-trends.php, stages/ecommerce/during/ecommerce-registrado.php, stages/ecommerce/post/ecommerce-registrado.php, stages/ecommerce/post/ecommerce.php
=> DS-4566-Ecommerce-post

src/1.0.0/js/homeDigital.js, stages/digital-trends/pre/digital-trends.php, stages/ecommerce/during/ecommerce-registrado.php
fix: add spinner in bta without form
=> DS-4629_fix_spinner

index.php, registrado.php, src/1.0.0/css/components/event-cards.css
=> DS-4464-Home-during

index.php, registrado.php, sponsors-registrado.php, src/1.0.0/css/pages/digital-trends.css, src/1.0.0/css/pages/ecommerce.css, src/components/speakers.php, stages/digital-trends/pre/digital-trends.php, stages/ecommerce/during/ecommerce-registrado.php, stages/ecommerce/during/ecommerce.php, stages/ecommerce/post/ecommerce-registrado.php
fix(emms): post demo modifications
=> DS-4633-Post-demo-modifications-v2

stages/ecommerce/during/ecommerce-registrado.php
=> DS-4633_fix_chat

utils/SpreadSheetGoogle.php
feat: add events columns in spread
=> DS-4606_fix_spread

relay-confirmation-email/during-ecommerce/durgin-ecommerce.html
fix(ecommerce): email corrections
=> Fix-ecommerce-during-email

speaker-interna.php, sponsors-interna.php, sponsors-registrado.php, sponsors.php, src/components/head-digitaltrends.php, src/components/head-speaker-interna.php, stages/digital-trends/pre/digital-trends-registrado.php, stages/digital-trends/pre/digital-trends.php
=> DS-4523-SEO-content

registrado.php, relay-confirmation-email/pre-ecommerce/20230228-EMMS.html, relay-confirmation-email/pre-template-email-register/20230228-EMMS.html, src/1.0.0/js/homeDigital.js, src/1.0.0/js/homeEcommerce.js, stages/digital-trends/during/digital-trends.php, stages/digital-trends/post/digital-trends.php, utils/Relay.php
related to: [DS-4635](https://makingsense.atlassian.net/browse/DS-4635)
[DS-4635]: https://makingsense.atlassian.net/browse/DS-4635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DS-4635 remove php extension

speaker-interna.php, src/1.0.0/css/scripts/speakerInternca.css, src/1.0.0/css/styles.css, src/1.0.0/js/speakersInterna.js
feat: add style used in speakerInterna script
feat: add show video and form logic
=> DS-4538_DS-4531_speaker-page-logic

src/components/head-speaker-interna.php
=> DS-4575_header_speaker

speaker-interna.php, src/components/head-digitaltrends.php, src/components/head-ecommerce.php, src/components/head-home.php, src/components/head-speaker-interna.php, src/components/head.php
=> DS-4523-SEO-content-v2

stages/ecommerce/post/ecommerce-registrado.php, stages/ecommerce/post/ecommerce.php
fix(ecommerce): starter sponsors
=> DS-4648-Fix-sponsors-media-partners-starters

index.php, registrado.php, src/components/cacheSettings.php, stages/digital-trends/pre/digital-trends-registrado.php, stages/digital-trends/pre/digital-trends.php, stages/ecommerce/during/ecommerce-registrado.php, stages/ecommerce/during/ecommerce.php
feat: add common header settings
=> DS-4656_common_settings

utils/Doppler.php
fix: change conditional validation
=> fix: change conditional validation

src/components/speakers.php, stages/ecommerce/post/ecommerce-registrado.php, stages/ecommerce/post/ecommerce.php
=> DS-4662-Speakers-by-event

registrado.php
=> DS-4688-Fix-cards-content

ediciones-anteriores-registrado.php, sponsors-registrado.php, src/1.0.0/js/previousEditions.js, src/1.0.0/js/sponsors.js
=> fix(forms): emails sending

stages/ecommerce/post/ecommerce-registrado.php
Changed modules order in Registered-Ecommerce
=> DS-4713-Change-modules-order

src/1.0.0/css/components/hero-registration.css, src/1.0.0/css/pages/digital-trends.css, stages/digital-trends/pre/digital-trends.php_backup
=> DS-4727-DT-Layout-module-1

src/1.0.0/css/components/grid.css, src/1.0.0/css/styles.css, stages/digital-trends/pre/digital-trends.php
=> DS-4733-DT-Layout-module-2

src/1.0.0/css/components/prices-plans.css, src/1.0.0/js/popUp.js, stages/digital-trends/pre/digital-trends.php
=> DS-4730_pop_up_register

index.php, registrado.php, src/1.0.0/css/components/event-cards.css, stages/ecommerce/post/ecommerce-registrado.php
**Changed october to november**
=> DS-4752-Change-october-to-november

src/1.0.0/css/components/prices-plans.css, stages/digital-trends/pre/digital-trends.php
fix: add class to popUp button
=> DS-4730_fix_button_popUp

src/1.0.0/js/collapsibles.js
fix: fix collapsible questions errors
chore: update collapsible legal listeners
chore: rename wrong functions name
chore: update collapsible list functions
=> DS-4768_collapsible_question_bug

src/1.0.0/css/components/prices-plans.css, src/1.0.0/css/pages/digital-trends.css, stages/digital-trends/pre/digital-trends.php
fix(digital-trends): visual corrections
=> DS-4729-Price-module-corrections

.gitignore, wix/readme, wix/v1/api/controllers/SubscriberController.php, wix/v1/api/models/SubscriberDatabase.php, wix/v1/api/models/SubscriberDopplerList.php, wix/v1/api/models/SubscriberWix.php, wix/v1/api/save_subscriber_data.php, wix/v1/api/utils/Logger.php, wix/v1/api/utils/toHex.php
Related to: [DS-4726](https://makingsense.atlassian.net/browse/DS-4726)
[DS-4726]: https://makingsense.atlassian.net/browse/DS-4726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DS-4726 API WIX

relay-confirmation-email/early-birds-digital-trends/early-birds-digital-trends.html, utils/Relay.php
=> DS-4772-Update-dt-email-content

src/1.0.0/css/components/prices-plans.css, src/1.0.0/css/general/constants.css, src/1.0.0/js/popUp.js, stages/digital-trends/pre/digital-trends.php
feat: add submit without forms
fix: change dt form buttons styles
=> DS-4788_fix_forms

src/1.0.0/css/components/speakers-vip.css, src/1.0.0/css/pages/digital-trends.css, src/1.0.0/css/styles.css, src/components/speakers__backup--ecommerce.php, stages/digital-trends/pre/digital-trends.php
feat(digital-trends): added calendar module
=> DS-4794-DT-Module-calendar-layout

index.php, registrado.php, stages/digital-trends/during/digital-trends-registrado.php, stages/digital-trends/during/digital-trends.php, stages/digital-trends/post/digital-trends-registrado.php, stages/digital-trends/post/digital-trends.php, stages/digital-trends/pre/digital-trends-registrado.php, stages/digital-trends/pre/digital-trends.php
=> DS-4728_change_navbar_items

src/1.0.0/css/components/hero-registration.css, src/img/icons/icon-arrow--white.svg, stages/digital-trends/pre/digital-trends-registrado.php
feat(digital-trends-registrado): layout
=> DS-4796-Registered-DT-layout

src/1.0.0/css/components/hero-registration.css, src/1.0.0/css/components/prices-plans.css, src/1.0.0/css/pages/digital-trends.css, stages/digital-trends/pre/digital-trends-registrado.php, stages/digital-trends/pre/digital-trends.php
feat(digital-trends-registrado): layout
=> DS-4796-Registered-DT-layout-v2

config.php, stages/digital-trends/during/digital-trends.php, stages/digital-trends/post/digital-trends.php, stages/digital-trends/pre/digital-trends.php
=> DS-4786_sponsors_list

ediciones-anteriores.php, services/register.php, sponsors.php, src/1.0.0/js/common/submitForm.js, src/components/intellInput.php, stages/digital-trends/pre/digital-trends.php, stages/ecommerce/post/ecommerce.php, utils/DB.php, utils/Doppler.php
feat: add const for intell input and extract to common file
feat: send phone values if exist
feat: add new fields
chore: refactoring function for custom fields
chore: indeed commit
=> DS-4814_add_news_fields

src/1.0.0/css/components/prices-plans.css, src/1.0.0/css/components/speakers-vip.css, src/1.0.0/css/pages/digital-trends.css, src/components/speakers.php, stages/digital-trends/pre/digital-trends.php
Digital Trend NO REGISTRADO: updated content
=> DS-4747-Update-content

ediciones-anteriores.php, sponsors.php, src/1.0.0/css/pages/digital-trends.css, stages/digital-trends/pre/digital-trends-registrado.php, stages/digital-trends/pre/digital-trends.php, stages/ecommerce/post/ecommerce.php
feat(digital-trends): updated content
=> DS-4747-Update-content-v2

src/1.0.0/js/phoneFlag.js, src/components/intellInput.php
feat: auto set flag country by ip
=> DS-4831_auto_set_flag_by_ip

ediciones-anteriores-registrado.php, ediciones-anteriores.php, index.php, registrado.php, sponsors-registrado.php, sponsors.php, src/1.0.0/css/components/speakers-vip.css, src/components/speakers.php, stages/digital-trends/pre/digital-trends-registrado.php, stages/digital-trends/pre/digital-trends.php, stages/ecommerce/post/ecommerce-registrado.php, stages/ecommerce/post/ecommerce.php
=> DS-4832-Flow-changes

ediciones-anteriores.php, sponsors.php, src/1.0.0/css/components/speakers-vip.css, src/components/speakers.php, stages/digital-trends/pre/digital-trends-registrado.php, stages/digital-trends/pre/digital-trends.php, stages/ecommerce/post/ecommerce.php
fix(digital-trends): updated content
=> DS-4747-Update-content-v3

index.php, registrado.php, stages/digital-trends/pre/digital-trends-registrado.php, stages/digital-trends/pre/digital-trends.php
fix(navbar): removed entradas menu
=> DS-4827-Navbar-changes

src/components/speakers.php, stages/digital-trends/pre/digital-trends-registrado.php, stages/digital-trends/pre/digital-trends.php
fix(digital-trends): updated content
=> DS-4747-Update-content-v4

src/1.0.0/css/components/speakers-vip.css, src/components/speakers.php
fix(speakers): vip and integration
=> DS-4840-Speakers-vip

ediciones-anteriores.php, sponsors.php
fix(sponsors-ediciones-anteriores): edited content
=> DS-4810-Edit-form-content

relay-confirmation-email/dt-earlybirds-wix/dt-earlybirds-wix.html, relay-confirmation-email/resumen-entrada-individual/resumen-entrada-individual.html, relay-confirmation-email/resumen-entrada-pack/resumen-entrada-pack.html
feat: change content and images
=> DS-4826_fix_emails

admin/speakers/edit_speakers.php
=> DS-4844_fix_edit_speaker

utils/Relay.php
=> DS-4834_add_wix_email_temapltes

src/1.0.0/js/user.js
=> DS-4858_fix_userid

src/components/speakers.php
fix: change speaker conditional
=> hot_fix_deplo_10042023

src/1.0.0/css/components/calendar.css
=> fix-speakers

config.php, stages/digital-trends/pre/digital-trends.php
fix(digital-trends): sponsors integration
=> DS-4861-DT-Sponsors-integration

sitemap.xml
=> DS-4860_update_sitemap

ediciones-anteriores.php, sponsors.php, src/1.0.0/css/components/calendar.css, src/1.0.0/css/components/speakers-vip.css, src/components/speakers.php
=> DS-4859-Fixes-post-deploy

sponsors.php, src/1.0.0/css/pages/sponsors.css
=> DS-4829-Fix-capsules

services/register.php
fix: solved undefined array key 1 warning
=> DS-4863_fix_register

admin/speakers/index.php
=> DS-4661_add_event_filyer

sponsors-registrado.php, sponsors.php, src/1.0.0/css/pages/sponsors.css
=> DS-4865-Sponsors-inactive-btn

stages/digital-trends/during/digital-trends-registrado.php, stages/digital-trends/during/digital-trends.php
fix(digital-trends): logged and no-logged
=> DS-4873-DT-During

index.php, registrado.php, src/components/cacheSettings.php
[feat: change cacheSetting to a single function to query per event](https://github.com/FromDoppler/emms23/commit/c87bdb11f6b5b509a43373e0de2feb11769f940e)
[feat: implement new function](https://github.com/FromDoppler/emms23/commit/4f0d4b2172b05f4f5e847e1bacf328be6333fc39)
=> DS-4872_change_cacheSettings.php

utils/DB.php
fix(DB): sponsors cards status
=> fix-sponsors-status

index.php, registrado.php
=> DS-4879-Config-DT-Home-cards

src/1.0.0/js/common/submitForm.js, src/1.0.0/js/user.js, stages/digital-trends/pre/digital-trends.php
fix: fix single event in localStorage
=> DS-4880_fix_events_form

campaignGenerator/exampleTemplate.html, campaignGenerator/massiveCampaignGenerator.php
feat: add massive campaing generator
=> DS-4870_massive_campaing_generator

campaignGenerator/exampleTemplate.html
=> DS-4870_edit_template

.docker/db/EMMS23.sql, .docker/db/queries/get_subscription_doppler_errors.sql, services/register.php, utils/DB.php, utils/subscriptionErrors.php, wix/v1/api/models/SubscriberDopplerList.php
related to [DS-4886](https://makingsense.atlassian.net/browse/DS-4886)
[DS-4886]: https://makingsense.atlassian.net/browse/DS-4886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DS-4886 storage subscription doppler list errors

descarga-certificado.php, src/1.0.0/css/pages/certificate-download.css, src/1.0.0/css/styles.css
=> DS-4882-Download-certificate-template

src/1.0.0/css/components/speakers-vip.css, src/components/speakers.php
fix(speakers): webflow changes
=> DS-4884-DT-webflow-changes-v2

src/1.0.0/js/popUp.js, src/components/intellInput.php, stages/digital-trends/pre/digital-trends-registrado.php, stages/digital-trends/pre/digital-trends.php
=> DS-4903_fix_multiple_from

services/register.php, utils/DB.php, utils/Validator.php
fix: cut the execution of the registry if there are validation errors and improvements in the update
=> DS-4867_fix_register

src/1.0.0/js/date.js, src/components/speakers.php
fix: hide speaker time if it does not exist
=> DS-4905_fix_speaker_without_time

src/1.0.0/js/date.js, src/components/speakers.php
fix: refactoring commong functions to change date
=> DS-4906_fix_newtworking_hour

descarga-certificado.php, speaker-interna.php, src/1.0.0/css/components/certificate-modal.css, src/1.0.0/js/certificate/certificateDt.js, src/1.0.0/js/certificate/certificateEcommerce.js, src/1.0.0/js/certificate/certificateWorkshop.js, src/1.0.0/js/common/certificate.js, stages/digital-trends/during/digital-trends-registrado.php, stages/ecommerce/during/ecommerce-registrado.php
[feat: add new certificate logic](https://github.com/FromDoppler/emms23/commit/57bc6decc653a48dc9a8816feb5ee22f967909c7)
=> DS-4904_DS-4897_add_new_certificate

src/1.0.0/css/components/prices-plans.css, stages/digital-trends/during/digital-trends-registrado.php, stages/digital-trends/during/digital-trends.php, stages/digital-trends/pre/digital-trends-registrado.php
=> DS-4873-During-files-revision

src/components/cacheSettings.php
Related to: https://makingsense.atlassian.net/browse/DS-4908
=> DS-4908 add dt cache current state

src/components/cacheSettings.php
related to: https://makingsense.atlassian.net/browse/DS-4908
=> DS-4908 fix cache name dt

stages/digital-trends/during/digital-trends-registrado.php, stages/digital-trends/during/digital-trends.php
=> DS-4873-During-files-revision-v3

stages/digital-trends/during/digital-trends-registrado.php, stages/digital-trends/pre/digital-trends-registrado.php
=> DS-4875_fix_links

src/1.0.0/css/components/header.css, src/1.0.0/css/components/hellobar.css, src/1.0.0/css/components/hero-registration.css, stages/digital-trends/pre/digital-trends-registrado.php
feat(digital-trends-registrado): added hellobar
=> DS-4910-DT-Registered-hellobar

utils/SpreadSheetGoogle.php
feat: add new fields in spread
=> DS-4911_add_new_fields_in_spread

index.php, registrado.php
fix(index-registrado): changed block to DT
=> DS-4891-Change-block-to-DT

src/1.0.0/js/common/certificate.js, textify/certificate-emms2023.php, textify/certificate-emms2023qa.php
=> DS-4898_add_workshop_logic

src/1.0.0/css/pages/digital-trends.css, stages/digital-trends/during/digital-trends.php, stages/digital-trends/post/digital-trends-registrado.php, stages/digital-trends/post/digital-trends.php, stages/ecommerce/post/ecommerce.php
=> DS-4913-DT-Post-files

stages/digital-trends/during/digital-trends-registrado.php, stages/digital-trends/during/digital-trends.php, stages/digital-trends/post/digital-trends-registrado.php, stages/digital-trends/post/digital-trends.php, stages/digital-trends/pre/digital-trends-registrado.php, stages/digital-trends/pre/digital-trends.php
fix(digital-trends): social share content changes
=> DS-4914-Fix-DT-share

index.php, registrado.php, src/1.0.0/css/pages/home.css
fix(home): mobile visual change
=> DS-4915-Fix-visual-home

stages/digital-trends/during/digital-trends.php, stages/digital-trends/post/digital-trends.php, stages/digital-trends/pre/digital-trends.php
fix: add date.js in digital-trends
=> DS-4933_add_datejs

stages/digital-trends/post/digital-trends-registrado.php, stages/digital-trends/post/digital-trends.php
fix(digital-trends): post stage
=> DS-4913-DT-Post-files-v2

stages/digital-trends/during/digital-trends-registrado.php, stages/digital-trends/post/digital-trends-registrado.php, stages/digital-trends/pre/digital-trends-registrado.php
fix(digital-trends-registrado): hide free plan in mobile
=> DS-4932-Hide-free-plan-in-mobile

index.php, registrado.php, src/1.0.0/css/components/hero-conference.css, stages/digital-trends/during/digital-trends-registrado.php, stages/digital-trends/during/digital-trends.php
fix(digital-trends): update during content
=> DS-4926-During-content

src/1.0.0/css/components/hero-conference.css, stages/digital-trends/during/digital-trends.php, stages/digital-trends/post/digital-trends.php
fix(digital-trends): popup and chat style
=> fixes-meet-predeploy

utils/Relay.php
fix: add dplrid in during DT email
=> DS-4603_fix_during_email_DT

descarga-certificado.php, src/1.0.0/js/certificate/certificateWorkshop.js, src/1.0.0/js/common/certificate.js
feat: add workshop certificate security
=> DS-4920_DS-4921_DS-4923_DS-4924_workshop_security

wix/v1/api/controllers/WixContactController.php, wix/v1/api/find_contact_by_email.php, wix/v1/api/models/WixContactsDatabase.php, wix/v1/api/update_contact_name.php
Related to:
https://makingsense.atlassian.net/browse/DS-4918
https://makingsense.atlassian.net/browse/DS-4919
=> DS-4918-DS-4919 find_contact_by_email & update_contact_name

stages/digital-trends/post/digital-trends-registrado.php, stages/digital-trends/post/digital-trends.php
=> DS-4925-Update-post-content

src/1.0.0/js/common/submitForm.js, src/1.0.0/js/user.js
=> DS-4935_fix_dplrid

src/1.0.0/js/date.js
Related to https://makingsense.atlassian.net/browse/DS-4936
=> DS-4936 fix date es

stages/digital-trends/during/digital-trends-registrado.php
fix(digital-trends-registrado): changed transition banner content
=> DS-4938-Change-transition-banner-content

src/1.0.0/js/commonAnimations.js
Related to: https://makingsense.atlassian.net/browse/DS-4934
=> DS-4934 fix blank screen on top

index.php, registrado.php, src/1.0.0/css/pages/home.css, stages/digital-trends/post/digital-trends-registrado.php, stages/digital-trends/post/digital-trends.php
fix(digital-trends - index): updated post content
=> DS-4925-Update-post-content-v2

speaker-interna.php, src/1.0.0/js/certificate/certificateSpeaker.js, stages/digital-trends/post/digital-trends-registrado.php, stages/digital-trends/post/digital-trends.php, stages/ecommerce/post/ecommerce-registrado.php, stages/ecommerce/post/ecommerce.php
feat: add abstract speaker certificate form
=> DS-4942_abstract_speaker_certificate

stages/digital-trends/post/digital-trends-registrado.php, stages/digital-trends/post/digital-trends.php, stages/ecommerce/post/ecommerce-registrado.php
fix(post): dt and ecommerce content changes
=> DS-4925-Update-post-content-v3

src/1.0.0/css/components/hero-registration.css, stages/digital-trends/post/digital-trends.php, stages/ecommerce/post/ecommerce.php
fix(hero-registration): logos marquee
=> DS-4944-Fix-logos-marquee

utils/subscriptionErrors.php
related to https://makingsense.atlassian.net/browse/DS-4972
=> DS-4972 fix catch error on subscription doppler list

src/1.0.0/css/pages/sponsors.css
=> /DS-4975-Sponsors-alignment

index.php, registrado.php, src/1.0.0/css/components/hero-registration.css, stages/digital-trends/post/digital-trends.php
fix(index-digital-trends): update content
=> DS-4981-General-changes
